# Created with PHPWatch/winget-pkgs - https://github.com/PHPWatch/php-winget-manifest
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: PHP.PHP-NTS.8.2
PackageVersion: 8.2.29
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: php.exe
    PortableCommandAlias: php
Commands:
  - php
  - php82
UpgradeBehavior: install
ReleaseDate: 2025-07-01
ArchiveBinariesDependOnPath: true
Installers:
  - Architecture: x64
    InstallerUrl: https://windows.php.net/downloads/releases/php-8.2.29-nts-Win32-vs16-x64.zip
    InstallerSha256: 8404a12bd421075060ae9f7ae988777a476807163d9d4c10e1ac55175976f5c0
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x64
  - Architecture: x86
    InstallerUrl: https://downloads.php.net/~windows/releases/php-8.2.29-nts-Win32-vs16-x86.zip
    InstallerSha256: bf88cf1e7303639db234766e9eeae19d6f0760da127d4ccfd88d4a1a412a8f69
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x86
ManifestType: installer
ManifestVersion: 1.10.0
