# Created with PHPWatch/winget-pkgs - https://github.com/PHPWatch/php-winget-manifest
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: PHP.PHP-NTS.8.4
PackageVersion: 8.4.12
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: php.exe
    PortableCommandAlias: php
Commands:
  - php
  - php84
UpgradeBehavior: install
ReleaseDate: 2025-08-26
ArchiveBinariesDependOnPath: true
Installers:
  - Architecture: x64
    InstallerUrl: https://windows.php.net/downloads/releases/php-8.4.12-nts-Win32-vs17-x64.zip
    InstallerSha256: 9955f021aeca980310e467e168df5c3ae933d99cbb4e4cc7de668558061fdeb3
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x64
  - Architecture: x86
    InstallerUrl: https://downloads.php.net/~windows/releases/php-8.4.12-nts-Win32-vs17-x86.zip
    InstallerSha256: cdec5781310f55542ceb643282bd10ea06e017801a794072eb90cd4d9459fff5
    Dependencies:
      PackageDependencies:
        - PackageIdentifier: Microsoft.VCRedist.2015+.x86
ManifestType: installer
ManifestVersion: 1.10.0
